version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "
      until pg_isready -h db -p 5432; do
        echo 'Aguardando o banco de dados...';
        sleep 2;
      done;
      python manage.py migrate &&
      python manage.py populate_db &&
      gunicorn --bind 0.0.0.0:8000 digital_wallet_api.wsgi"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_data: